language: android        # 声明构建语言环境
jdk: oraclejdk8          # 下载jdk8

sudo: false              # 开启基于容器的Travis CI任务，让编译效率更高。

android:
  components:            # 配置信息
    - platform-tools
    - tools
  # The BuildTools version used by your project
    - build-tools-25.0.0
  # The SDK version used to compile your project
  # - android-22
    - android-25
  # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - addon-google_apis-google-21
    - extra-android-m2repository     # Android Support Repository
    - extra-android-support          # Support Library
  # - sys-img-armeabi-v7a-android-22
  # - extra-android-m2repository


script:
    - ./gradlew assemble